Moved warning prompts into user_warning() for better reuse

diff --git a/automagic-kernel-upgrade b/automagic-kernel-upgrade
--- a/automagic-kernel-upgrade
+++ b/automagic-kernel-upgrade
@@ -9,6 +9,19 @@ get_versions () {
   wget -q -O - "${URL}" | grep "href=\"v" | cut -d \" -f8
 }
 
+user_warning() {
+  WARNING_MESSAGE="${1}"
+
+  echo "$WARNING_MESSAGE"
+
+  read INPUT
+
+  if [ "${INPUT}" != "y" ]; then
+    echo "Aborting."
+    exit 1
+  fi
+}
+
 if [ "$(uname -i)" = "x86_64" ]; then
   ARCH="amd64"
 else
@@ -27,14 +40,7 @@ echo -n "Finding latest kernel .."
 
 VERSION="$(get_versions "${URL}" | tail -n 1)"
 
-echo ".. latest version is ${VERSION} for ${ARCH}. Continue? [y/n]"
-
-read INPUT
-
-if [ "${INPUT}" != "y" ]; then
-  echo "Aborting."
-  exit 1
-fi
+user_warning ".. latest version is ${VERSION} for ${ARCH}. Proceed to download kernel? [y/n]"
 
 TEMP_DIR="$(mktemp -d)" || exit 1
 trap 'rm -rf "${TEMP_DIR}"' EXIT
@@ -48,14 +54,7 @@ while read LINK; do
   wget "${DIRECTORY}${LINK}" -P "${TEMP_DIR}"
 done
 
-echo "WARNING: Installing this kernel can break your system. Continue? [y/n]"
-
-read INPUT
-
-if [ "${INPUT}" != "y" ]; then
-  echo "Aborting."
-  exit 1
-fi
+user_warning "WARNING: Installing this kernel can break your system. Continue? [y/n]"
 
 dpkg -i "${TEMP_DIR}"/*.deb
 
