Added check for superuser privileges

diff --git a/automagic-kernel-upgrade b/automagic-kernel-upgrade
--- a/automagic-kernel-upgrade
+++ b/automagic-kernel-upgrade
@@ -2,6 +2,11 @@
 
 set -e
 
+if [ "$(id -u)" -ne 0 ]; then
+  echo "ERROR: this program requires superuser privileges. Aborting."
+  exit 1
+fi
+
 URL="http://kernel.ubuntu.com/~kernel-ppa/mainline/"
 
 get_versions () {
